package error_utils

func Throw(v uint) {
	panic(v)
}
